version: 2.1

jobs:
  deployment:
    docker:
      - image: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine  # Imagem Docker com gcloud e kubectl pré-instalados

    steps:
      - checkout  # Faz checkout do código-fonte do repositório

      # Salva a chave de serviço em um arquivo temporário
      - run:
          name: "Salvar chave de serviço"
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS_JSON | base64 -d > /tmp/gcloud-key.json
            export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud-key.json"

      # Autenticação com as credenciais do Kubernetes
      - run:
          name: "Autorizar Credenciais"
          command: |
            gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
            gcloud container clusters get-credentials meu-cluster --zone us-central1-a --project meu-projeto

      # Agora o login no cluster é feito após a autorização
      - run:
          name: "Cluster login"
          command: "kubectl cluster-info"  # Executa o comando kubectl cluster-info para obter informações do cluster

workflows:
  deployment-workflow:
    jobs:
      - deployment: 
          context: default # Define que o job "deployment" será executado no workflow
