version: 2.1

jobs:
  deployment:
    docker:
      - image: cimg/base:current

    steps:
      
      - checkout
      - run:
          name: "Cluster info"
          command: "kubectl cluster-info"


workflows:
  deployment-workflow: 
    jobs:
      - deployment

      