version: 2.1

jobs:
  deployment:
    docker:
      - image: gcr.io/google.com/cloudsdktool/google-cloud-cli:alpine  # Imagem Docker com gcloud e kubectl pré-instalados

    steps:
      - checkout  # Faz checkout do código-fonte do repositório

      # Passo para instalar o kubectl
      - run:
          name: "Instalar kubectl"
          command: |
            echo "Instalando o kubectl..."
            curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
            chmod +x ./kubectl
            mv ./kubectl /usr/local/bin/kubectl
            kubectl version --client  # Verificar a instalação do kubectl

      # Salva a chave de serviço em um arquivo temporário
      - run:
          name: "Salvar chave de serviço"
          command: |
            echo $GOOGLE_APPLICATION_CREDENTIALS_JSON | base64 --decode > /tmp/gcloud-key.json
            export GOOGLE_APPLICATION_CREDENTIALS="/tmp/gcloud-key.json"
            cat /tmp/gcloud-key.json

      # Autenticação com as credenciais do Kubernetes
      - run:
          name: "Autorizar Credenciais"
          command: |
            cat /tmp/gcloud-key.json
            gcloud auth activate-service-account --key-file=/tmp/gcloud-key.json
            gcloud container clusters get-credentials my-cluster --zone us-central1-a --project original-nation-453118-a7

      # Agora o login no cluster é feito após a autorização
      - run:
          name: "Cluster login"
          command: "kubectl cluster-info"  # Executa o comando kubectl cluster-info para obter informações do cluster

workflows:
  deployment-workflow:
    jobs:
      - deployment:
          context: default  # Define que o job "deployment" será executado no workflow
